tmz 3.1.0 enhancement morse gerke steinheil
S-Man42/GCWizard pull request #1584
Opened 2024-01-05 21:30 UTC by t-m-z

add three tables
- Original Code from Vail
- Gerke
- adapted Steinheil

2024-01-08 18:54 UTC, t-m-z commented on lib/application/registry.dart
I thought we agreed to keep the selections without  searchstrings

2024-01-08 19:08 UTC, Mike-3 commented on lib/application/registry.dart
I mean the symbol tables. The Morse symbol table is already there.

2024-01-08 19:23 UTC, t-m-z commented
done

2024-01-12 11:30 UTC, Mike-3 commented on lib/tools/crypto_and_encodings/morse/logic/morse.dart
> +  MORSE_CODE.AMERICAN: 'Morse',
Now I have the same text ("Morse") in the field at the top, no matter which Morse version I select.

2024-01-21 09:16 UTC, t-m-z commented on lib/tools/crypto_and_encodings/morse/logic/morse.dart
> +  MORSE_CODE.AMERICAN: 'Morse',
Changed

2024-01-22 20:52 UTC, Mike-3 requested changes

2024-01-22 20:52 UTC, Mike-3 commented on lib/tools/crypto_and_encodings/morse/widget/morse.dart
> +                child: i18n(context, mode.value + '_title'),
![image](https://github.com/S-Man42/GCWizard/assets/70719484/697613d3-931f-4c90-8152-59a1dcee0de2)
Missing item text

2024-01-22 21:18 UTC, t-m-z commented on lib/tools/crypto_and_encodings/morse/widget/morse.dart
> +                child: i18n(context, mode.value + '_title'),
corrected

2024-01-23 12:51 UTC, Mike-3 commented on lib/tools/crypto_and_encodings/morse/logic/morse.dart
> +  MORSE_CODE.AMERICAN: 'Morse',
I also noticed differences in the symbol tables and the selectable buttons in the widget.

Steinheil - no dash in the widget (only 2 * dot)
Morse 1838 - in the symbol table I only see short lines, long lines and dots. There is even more to choose from in the widget
Morse 1844 - I only see a short line in the symbol table. There is even more to choose from in the widget

2024-01-24 21:43 UTC, t-m-z commented on lib/tools/crypto_and_encodings/morse/logic/morse.dart
> +  MORSE_CODE.AMERICAN: 'Morse',
Steinheil: thats correct: Steinheil has no dash - only two dots at different heights
Morse 1838: corrected - was a failure while cleaning to much up
Morse 1844: thats okay: there are three differente dashes: 0, L and T

2024-01-25 16:49 UTC, merged