tmz 3.1.0 feature checkdigits
S-Man42/GCWizard pull request #1585
Opened 2024-01-05 21:40 UTC by t-m-z

- IMEI
- IBAN
- Euro
- DEU Tax ID
- EAN/GTIN
- Credit Cards
- ISBN

2024-01-07 19:55 UTC, Mike-3 requested changes

2024-01-07 19:55 UTC, Mike-3 commented on lib/tools/science_and_technology/checkdigits/logic/checkdigits__datatypes.dart
> +final Map<String, String> ID_LETTERCODE = {
as const if possible

2024-01-07 19:55 UTC, Mike-3 commented on lib/application/searchstrings/assets/common.json
> +  "checkdigits": "imei, isbn, ean, gtin, uic, euro, iban, 13616, visacard, mastercard, americanexpress, dinersclub",
remove comma

2024-01-07 19:55 UTC, Mike-3 commented on lib/tools/science_and_technology/checkdigits/logic/checkdigits_creditcard.dart
> +final Map<String, String> CHECKDIGITS_CREDITCARD_MMI = {
to const

2024-01-07 19:55 UTC, Mike-3 commented on lib/tools/science_and_technology/checkdigits/logic/checkdigits_creditcard.dart
> +final Map<String, String> CHECKDIGITS_CREDITCARD_PREFIX = {
to const

2024-01-07 19:55 UTC, Mike-3 commented on lib/tools/science_and_technology/checkdigits/logic/checkdigits_creditcard.dart
> +final Map<int, List<Object>> CHECKDIGITS_CREDITCARD_CARDSCHEMES = {
to const

2024-01-07 19:55 UTC, Mike-3 commented on lib/tools/science_and_technology/checkdigits/logic/checkdigits.dart
> +final _ITERATE_ALPHA = [
to const

2024-01-07 19:55 UTC, Mike-3 commented on lib/tools/science_and_technology/checkdigits/logic/checkdigits.dart
> +final _ITERATE_ALPHANUMERIC = [
to const
....

2024-01-07 19:55 UTC, Mike-3 commented on lib/tools/science_and_technology/checkdigits/widget/base/checkdigits_calculate_checkdigit.dart
![grafik](https://github.com/S-Man42/GCWizard/assets/70719484/4b699549-218e-4196-9ea1-dd5b35a9b894)
Check Credit Card Number
Adjust column widths if possible.

2024-01-07 19:55 UTC, Mike-3 commented on lib/tools/science_and_technology/checkdigits/widget/base/checkdigits_calculate_checkdigit.dart
Check Credit Card Number
Get Bank/Card Details

No Feedback. 
![grafik](https://github.com/S-Man42/GCWizard/assets/70719484/9ab3766e-599a-46cb-b4c8-888f5aa8ac29)
Or Percent feedback possible ?

We need Internetis not recognizable that way  ?
If so, please ask whether it is ok to integrate or expand the button text.
Maybe something like geohashing.
If so, please integrate a query as to whether it is ok.
Maybe something like geohashing.

2024-01-07 19:55 UTC, Mike-3 commented on lib/tools/science_and_technology/checkdigits/widget/base/checkdigits_calculate_checkdigit.dart
Calculate Credit Card Number
![grafik](https://github.com/S-Man42/GCWizard/assets/70719484/ec2ebb7a-ae06-4b54-a348-07dfcca2952d)
no Output ??

2024-01-07 19:55 UTC, Mike-3 commented on lib/tools/science_and_technology/checkdigits/widget/base/checkdigits_calculate_checkdigit.dart
Check Credit Card number
![grafik](https://github.com/S-Man42/GCWizard/assets/70719484/43ff0d11-25c2-4a78-9a3b-4cc42fea1b58)
Input: ? and CreditCardnumber (from clipboard) ?1234 1234

2024-01-07 19:55 UTC, Mike-3 commented on lib/tools/science_and_technology/checkdigits/widget/base/checkdigits_calculate_checkdigit.dart
![grafik](https://github.com/S-Man42/GCWizard/assets/70719484/17195ee3-9f2e-4afd-8558-ab855b160285)
 Output also with blocks XXXX XXXX XXXX XXXX

2024-01-10 18:34 UTC, S-Man42 commented
I just had a quick view to the UIC tests. But here I cannot see any cases with too long or too short numbers. I guess, there are no such tests elsewhere. Maybe you should focus a bit on edge and invalid cases :)

Could you do me a favor and add 91 80 6493 296-1 to the tests? :) It's my favorite engine ;)

2024-01-21 13:15 UTC, t-m-z commented on lib/application/category_views/all_tools_view.dart
> +import 'selector_lists/checkdigits/checkdigits_selection.dart';
sorry - I do not understand this hint

2024-01-21 13:18 UTC, t-m-z commented on lib/application/searchstrings/assets/common.json
> +  "checkdigits": "imei, isbn, ean, gtin, uic, euro, iban, 13616, visacard, mastercard, americanexpress, dinersclub",
done

2024-01-21 13:18 UTC, t-m-z commented on lib/tools/science_and_technology/checkdigits/logic/checkdigits__datatypes.dart
> +final Map<String, String> ID_LETTERCODE = {
done

2024-01-21 13:22 UTC, t-m-z commented on lib/tools/science_and_technology/checkdigits/logic/checkdigits.dart
> +final _ITERATE_ALPHA = [
done

2024-01-21 13:22 UTC, t-m-z commented on lib/tools/science_and_technology/checkdigits/logic/checkdigits.dart
> +final _ITERATE_ALPHANUMERIC = [
done

2024-01-21 13:22 UTC, t-m-z commented on lib/tools/science_and_technology/checkdigits/logic/checkdigits_creditcard.dart
> +final Map<String, String> CHECKDIGITS_CREDITCARD_PREFIX = {
done

2024-01-21 13:22 UTC, t-m-z commented on lib/tools/science_and_technology/checkdigits/logic/checkdigits_creditcard.dart
> +final Map<String, String> CHECKDIGITS_CREDITCARD_MMI = {
done

2024-01-21 14:45 UTC, t-m-z commented on lib/tools/science_and_technology/checkdigits/widget/base/checkdigits_calculate_checkdigit.dart
1. Check Credit Card Number - Adjust column widths if possible.
   its a lucky game - I did some tests and hope this fits better
   
2. Check Credit Card Number - Get Bank/Card Details - No Feedback.
   - Question/Dialog added
   - percentage not possoble - I do not know what is 100 percent
   
3. Calculate Credit Card Number - No output
   if there is no question marke there is nothing to calculate
   => now there is a check and a hint
   
4. Check Credit Card number - Input: ? and CreditCardnumber (from clipboard) ?1234 1234 - Format exception
   check and corresponding hint added
   
5. Calculate Check digit Output also with blocks XXXX XXXX XXXX XXXX
    format-method added

2024-02-03 13:16 UTC, t-m-z commented on lib/application/category_views/all_tools_view.dart
> +import 'selector_lists/checkdigits/checkdigits_selection.dart';
found the tomatoes and removed them.

2024-02-15 22:33 UTC, t-m-z commented on lib/application/category_views/all_tools_view.dart
> +import 'selector_lists/checkdigits/checkdigits_selection.dart';
changes are done within the branch. The master ist damaged. I made a pull request

2024-02-16 10:29 UTC, S-Man42 commented
![grafik](https://github.com/S-Man42/GCWizard/assets/16626063/73229233-d0ad-4769-a50e-9f0bcd09437f)

I find it strange, that everythings starts with capital letter except "card". Please make it capital too

2024-02-16 10:31 UTC, S-Man42 commented
Please add used APIs into the APIs sections of the licenses (at least the bank api): 
![grafik](https://github.com/S-Man42/GCWizard/assets/16626063/7a923efd-68a6-456f-83af-024b8167ff15)

And could you please rename the section to "Used APIs" in that doing?

2024-02-16 10:33 UTC, S-Man42 commented
![grafik](https://github.com/S-Man42/GCWizard/assets/16626063/9bab4562-d97c-415d-bf68-a5250883a3e3)

That looks strange from my point of view. Is it meant this way? What should a user read from this?

2024-02-16 10:35 UTC, S-Man42 commented
978-3-7529-6734-0

How do I enter this IBAN?

2024-02-16 10:40 UTC, S-Man42 commented
![grafik](https://github.com/S-Man42/GCWizard/assets/16626063/2e3a04b4-77d6-4b64-9f17-3a857373ab43)

The line break in the numbers are not necessary, I guess. I believe it comes from too small columns which result that you added the third column for the country, right? Maybe it is the better choice to but DE and Deutschland together into one column (maybe "DE (Deutschland)" or just leave the country code because you can read it from the IBAN itself?) to do not need a break of the numbers

2024-02-16 10:42 UTC, S-Man42 commented
![grafik](https://github.com/S-Man42/GCWizard/assets/16626063/11f4f257-d4a0-4aff-a218-9ce0cbf69524)
 "digit" capital letter, see above. 

Generally: The pattern in the app is: Titles are capitalized, descriptions are normal English writing, means nearly always small letters.

2024-02-16 10:44 UTC, S-Man42 commented
![grafik](https://github.com/S-Man42/GCWizard/assets/16626063/607a8d55-2c0a-4c04-8ab5-89203750e509)

Why is here a line break?
Isnt it interesting to see the reason how you identify the printing organisation? (i dont know, is there a code for that, maybe the RB?)

2024-02-16 11:33 UTC, t-m-z commented
That's not an iban but isbn

Sent from MailDroid

-----Original Message-----
From: MLorenz42 ***@***.***>
To: S-Man42/GCWizard ***@***.***>
Cc: Thomas ***@***.***>, Author ***@***.***>
Sent: Fr., 16 Feb. 2024 10:35
Subject: Re: [S-Man42/GCWizard] tmz 3.1.0 feature checkdigits (PR #1585)

978-3-7529-6734-0

How do I enter this IBAN?

-- 
Reply to this email directly or view it on GitHub:
https://github.com/S-Man42/GCWizard/pull/1585#issuecomment-1948132472
You are receiving this because you authored the thread.

Message ID: ***@***.***>

2024-02-16 12:28 UTC, S-Man42 commented
I already saw my mistake and deleted the question ;)

2024-02-18 09:24 UTC, t-m-z commented
refactor of widget is donw, requested changes are done

2024-02-28 06:05 UTC, S-Man42 commented
For me still cryptic hint texts (nightly build)
![Screenshot_20240228_070221](https://github.com/S-Man42/GCWizard/assets/16626063/540c3e10-883f-4565-8afe-de9153c424e7)

2024-02-28 06:07 UTC, S-Man42 commented
Could you please adjust search strings. Was not able to find the Euro tool with "money" maybe there are some good additional strings for the tools :)

Moreover: Are you quite sure about "Euro bill"? I cant find "bill" in any dictionary for Banknote or Geldschein. It is banknote as far as I can see.

2024-03-05 08:24 UTC, merged