tmz 3.1.0 feature battleship
S-Man42/GCWizard pull request #1610
Opened 2024-01-28 15:02 UTC by t-m-z

2024-02-07 18:42 UTC, Mike-3 commented
![image](https://github.com/S-Man42/GCWizard/assets/70719484/08df8237-cbf2-432e-af09-2c12b25f0499)

Exception

2024-02-07 18:42 UTC, Mike-3 requested changes

2024-02-07 18:42 UTC, Mike-3 commented on lib/tools/crypto_and_encodings/battleship/logic/battleship_data.dart
> +final Map<String, List<String>> BATTLESHIP_ALPHABET = {
Change to const

2024-02-07 21:46 UTC, t-m-z commented on lib/tools/crypto_and_encodings/battleship/logic/battleship_data.dart
> +final Map<String, List<String>> BATTLESHIP_ALPHABET = {
done

2024-02-07 22:16 UTC, t-m-z commented on lib/tools/crypto_and_encodings/battleship/logic/battleship_data.dart
> +final Map<String, List<String>> BATTLESHIP_ALPHABET = {
exception caught, tests will follow

2024-02-08 16:32 UTC, Mike-3 commented
![grafik](https://github.com/S-Man42/GCWizard/assets/70719484/e4c3bf09-8a54-4959-a30f-b7dbab602b62)

Out of Memory Exception -> Limitation

2024-02-08 21:57 UTC, t-m-z commented
valid point. I am still not experienced enough in testing and I still believe the users are good

2024-02-09 07:55 UTC, Mike-3 commented
Mayby the user, but not the tester ;-)
Don't forget to change to default decrypt.

2024-02-09 09:16 UTC, merged