Randomizer
S-Man42/GCWizard pull request #1955
Opened 2024-10-11 15:40 UTC by S-Man42

2024-10-13 13:01 UTC, Mike-3 commented
I think it is better to flip the output from coin flipper.
![image](https://github.com/user-attachments/assets/e00fd552-a50e-472f-a699-84042d29c7ea)

2024-10-13 15:18 UTC, S-Man42 commented
> I don't understand the point of List Elements.

Like a Formula: You can create a List of whatever. (First you name the list, click on it, create elements, exactly the Formula workflow). And thrn you are able to do random operations on this custom list. Maybe chose two  soccer teams out of 18 to olay against another

2024-10-13 15:20 UTC, S-Man42 commented
List is thr important thibg to review because of the actual persist operations (save, update, delete to preferences)

2024-10-13 22:06 UTC, S-Man42 commented
> I think it is better to flip the output from coin flipper.
Done

2024-10-15 15:03 UTC, Mike-3 commented
Im List Elements Edit List anwählen und ohne etwas zu ändern wieder mit dem Haken bestätigen ändert den List Namen.
![image](https://github.com/user-attachments/assets/6362b29d-056e-4f0f-8351-4c98cb2cce67)

2024-10-15 15:08 UTC, Mike-3 commented
Das hinzufügen von Einträgen ist anders als bei allen anderen unseren List Editoren Formelrechner, Alphabet, ..). Ist das unbedingt notwendig ?
Normalerweise ist ja das Eingabefeld neben dem + und wird dann mit + an die Liste angehängt.
![image](https://github.com/user-attachments/assets/16591f37-d78c-4b9a-849d-c502ddcb517d)

2024-10-15 15:17 UTC, Mike-3 commented
Nicht editierbare Eintrage nach mehrfachen drücken vom +
![image](https://github.com/user-attachments/assets/088de0ff-4e1b-4004-8ba0-db827eeb75bc)

2024-10-15 15:50 UTC, Mike-3 commented
Warum ist das Einheiten DropDown größer als das DropDown der Koordinaten ?
![image](https://github.com/user-attachments/assets/bb84e716-a616-4928-b70b-fdaaa1180b6d)

2024-10-15 16:05 UTC, Mike-3 requested changes

2024-10-15 18:47 UTC, S-Man42 commented
> Im List Elements Edit List anwählen und ohne etwas zu ändern wieder mit dem Haken bestätigen ändert den List Namen.

Igitt

2024-10-15 18:49 UTC, S-Man42 commented
> Das hinzufügen von Einträgen ist anders als bei allen anderen unseren List Editoren Formelrechner, Alphabet, ..). Ist das unbedingt notwendig ? Normalerweise ist ja das Eingabefeld neben dem + und wird dann mit + an die Liste angehängt.

Habe keine andere Lösung gefunden leider. Irgendwie hat der Controller im Zusammenspiel mit den Preferences sonst Murks gemacht. Das ist in der Tat anders als bei den anderen Widgets und würde ich erstmal so belassen, auch wenn ich selbst das nicht so geil finde...

2024-10-15 18:49 UTC, S-Man42 commented
> Nicht editierbare Eintrage nach mehrfachen drücken vom +

Was bedeutet nicht editierbar? Kannst du nicht auf Edit drücken?

2024-10-15 18:51 UTC, S-Man42 commented on lib/common_widgets/gcw_stringlisteditor.dart
> +  String? _editValue;
Nein, wird irgendwo wieder null gesetzt, wenn nichts editiert wird. Halte ich für korrekt

2024-10-15 18:52 UTC, S-Man42 commented on lib/tools/crypto_and_encodings/substitution/widget/substitution.dart
> +          title: i18n(context, 'substitution_generate_to'),
Weil "to" zwei Bedeutungen im Deutschen hat: Bis und Nach. Passt halt mal so und mal so. Deswegen habe ich mich entschieden, kein  common_to mehr zu haben, sondern je nach fall entscheiden zu lassen. Sonst isses, wie hier, schlicht falsch

2024-10-15 18:53 UTC, S-Man42 commented on lib/tools/general_tools/randomizer/logic/randomizer.dart
> +  return Random().nextDouble() * (end - start) + start;
nextDouble gibt 0 bis 1 aus, nextInt gibt 0 bis Range aus.

2024-10-16 18:29 UTC, Mike-3 commented
> > Nicht editierbare Eintrage nach mehrfachen drücken vom +
> 
> Was bedeutet nicht editierbar? Kannst du nicht auf Edit drücken?

War falsch von mir interpretiert. Sah irgendwie komisch aus.

2024-10-18 16:24 UTC, merged